### PR TITLE
fix(ejs):  Prevent the language from being set

### PR DESCRIPTION
**Pull request by EYHN**
**Contributing rules**

- Fork the repo and create your branch from `canary`. Then be sure to put the `canary` branch as the target for your pull request.
- Please be sure to follow the [contributing guidelines](https://github.com/viosey/hexo-theme-material/blob/master/CONTRIBUTING.md), especially for commit message
- Remove the `Contributing rules` part from this description
- Fill out the other parts from this description

**What kind of change does this PR introduce?** (check one with "x")

- [x] Bug fix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

____

**Description**

Prevent the language from being set to cause an error

防止因为未设置语言，而报错。

____

**Verification steps**

No verification steps.

### CODE REVIEW

**Comment by neoFelhz** [comment]
I think we don't need this. We shouldn't support users who didn't configure well. That's their fault.

**Comment by EYHN** [comment]
配置文件应该有默认值 软件不应该因为配置文件而出现异常

**Comment by neoFelhz** [comment]
No. If users have alreday read the docs carefully, then they will configure it right and it won't cause any problem.
As I said, that's because their fault. We know that Hexo has their own config file configuring language with empty default so it must have their reson.

**Comment by neoFelhz** [comment]
Although there are more and more users open some issues about this, but I still think I should reject this PR. In my opinion, we should not be obliged to be responsible for users who do not read the docs.

**Pull request closed without merging**
