### PR TITLE
Update: use PaceJS instead of NProgress

### PR DESCRIPTION
**Pull request by Halyul**
**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bug fix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [x] Yes
- [ ] No

____

**Description**

No description.

____

**Verification steps**

No verification steps.

### CODE REVIEW

**Comment by Halyul** [comment]
It seems that center-atom's and center-radar's styles are conflicting with the original style.css, but I can't find the conflict part(s), so these two styles are unavailable now.

**Comment by pidupuis** [comment]
@Halyul for the two conflicting styles, maybe try using `!important` after css rules

**Comment by Halyul** [comment]
@pidupuis OK, I will try to solve it.

**Comment by pidupuis** [comment]
@Halyul if you can't solve it, I suggest you to remove these two styles if they does not work

**Pull request merged**
