### PR TITLE
refactor(language): improve language fault tolerance

### PR DESCRIPTION
**Pull request by cubesky**
**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

____

**Description**

Allow site config language is null. Improve fault tolerance. 

____

**Verification steps**

No verification steps.

### CODE REVIEW

**Comment by EYHN** [comment]
这让我想起我逝去的PR #222

**Comment by cubesky** [comment]
@EYHN (￣∇￣) 我也不知道能不能通过....

**Comment by neoFelhz** [comment]
Come on. Just as I said before. If users can not configure their config file carefully,  we shouldn't be obliged to be responsible for them.
Hexo as well as us had writen the docs very carefully. We even shouldn't give support for them.

**Comment by EYHN** [comment]
23333 笑出声 真的

**Pull request merged**
