### PR TITLE
1.3.0

### PR DESCRIPTION
**Pull request by viosey**
## New features
- feat(keywords): add post keywords as meta keywords #138 
- feat(analytics): add analytics id function #147 
- feat(opengraph): add opengraph support for posts #149 
- feat(pin): support pin posts on the top of the list #150 
- feat(ui): custom elevation for posts #158 
- feat(load): add a javascript load queue #159 
- feat(sidebar_footer_image): add sidebar footer image config #160 
- feat(sidebar): add support for customize sidebar #165 
- feat(highlight): remove highlight.js #174 
- feat(gallery): use lazyload #175 
- feat(sidebar): can hide divider and footer  #176 
- feat(progressbar): custom style functino and revert center-atom style #178 

## Changes
- chore(doc): add issue template
- chore(doc): add pr template
- chore(doc): add branch detail
- chore(doc): add contributing.md
- chore(contributing): update master from canary #163 
- refactor(config): rename _config to _config.example #142 
- refactor(template): add more details #153 

## Bugs fixed
- fix(#168): stops browsers covering up search suggestions #170 
- fix(autocomplete): disable browser autocomplete #171

### CODE REVIEW

**Comment by Kitcham** [comment]
pl

**Comment by cubesky** [comment]
It seems I will need more time to write docs...

**Comment by neoFelhz** [comment]
Well. We have already made a great changes and now we are actually ready forcrealease a great version!

**Comment by cubesky** [comment]
* feat(ui): use Pace.js instead of NProgress #173 

This should be revert. Remove it from feature list.

**Comment by cubesky** [comment]
fix a button style pollution when using `disqus_click`

**Comment by neoFelhz** [comment]
I've already update the verison code in README.md and package.json.

**Pull request merged**
