### PR TITLE
feat(sponsor): add CC_BY license

### PR DESCRIPTION
**Pull request by simonsmh**
https://github.com/viosey/hexo-theme-material/pull/140

### CODE REVIEW

**Comment by neoFelhz** [comment]
Please

**Comment by pidupuis** [comment]
@neoFelhz he lets the upyun icon but moves it inside `sponsor`

**Comment by neoFelhz** [comment]
@pidupuis Yep,I found him delete that the line in _config.yml as well.

**Comment by simonsmh** [comment]
1. 我没有删，请自行阅读代码
2. 这样作是为了方便其它用户添加存放于此的同类信息，与cc_by并无直接联系，只是为了作演示

**Comment by simonsmh** [comment]
为了取消误解，我过两天再po个sponsor过来，跟cc_by分开吧

**Pull request closed without merging**
