### PR TITLE
feat(sidebar): add capability to change the sidebar options order

### PR DESCRIPTION
**Pull request by Halyul**
**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bug fix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [x] Yes
- [ ] No

____

**Description**

User can change the sidebar options order.
用户可以自定义侧边栏选项顺序。
8ff16bfb-6dfd-4a91-88ac-bf974d305e4e
0b78b724-9caa-4bd3-9aa9-7c570fdf8859

____

**Verification steps**

No verification steps.

### CODE REVIEW

**Comment by Halyul** [comment]
If user dont use some items, it/they wont be generated

**Comment by neoFelhz** [comment]
@Halyul You mean when the item won't shown if user deletes the configurations in the config file?

**Comment by Halyul** [comment]
Yes

**Comment by neoFelhz** [comment]
@Halyul I see. It is not so intuitional as using `true` or `false`, don't you think?

**Comment by Halyul** [comment]
Just tell them the options can be deleted!

**Pull request closed without merging**
