### PR TITLE
feat(comments): add "Disqus_click_to_load" to improve in-GFW-users

### PR DESCRIPTION
**Pull request by Kitcham**
**Contributing rules**

- Fork the repo and create your branch from `canary`. Then be sure to put the `canary` branch as the target for your pull request.
- Please be sure to follow the [contributing guidelines](https://github.com/viosey/hexo-theme-material/blob/master/CONTRIBUTING.md), especially for commit message
- Remove the `Contributing rules` part from this description
- Fill out the other parts from this description

**What kind of change does this PR introduce?** (check one with "x")

- [x] Bug fix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

____

**Description**
### English：

- Add a way to load  Disqus comments：“Dissqus_click_to_load”. It means that Disqus will be load after your click. Useful as it is, it help improve  experience of Chinese who are trapped by the GFW so that avoid  progress bar pause.

- The style of “Read Comments” button is based on Material Design, Click-effect will be added next release

- Thanks to button's js git: https://github.com/davinder17s/material-ripple-effect

- Add multilingual support for the button and fix the text in the button: "Read Comments 「Be sure 'disq.us & disquscdn.com & disqus.com' can be loaded 」" (IN https://github.com/viosey/hexo-theme-material/pull/182/commits/dbef40cec50fa488e33d8806232ea41d9218fc26 )
### 中文：

- 增加一种Disqus的手动加载方式，点击后加载Disqus评论。对墙内用户更加友好，避免有部分浏览器加载卡进度条（如Via，Chrome等浏览器）

- 采用MD风格的”阅读评论“ button

- button的JS引用自: https://github.com/davinder17s/material-ripple-effect

- 增加了手动加载button的文字提示：“阅读评论 「请确保 disq.us & disquscdn.com & disqus.com 可以正常加载」”，并加入多语言支持 （在 https://github.com/viosey/hexo-theme-material/pull/182/commits/dbef40cec50fa488e33d8806232ea41d9218fc26 中）
___

**Verification steps**
- Open ` /material/_config.yml  `. Input below at` Line 170 ` to turn on.
>comment:
         use: disqus_click

- `hexo g`,you will see the different

### CODE REVIEW

**Comment by neoFelhz** [comment]
Well,I personally think we needn't that button.This theme is face to users from the whole world.Not all the countries have the same Internet problem like China.So I think we need a way to judge whether the vistor can load Disqus or not,then decide if it is nesscary to load Disqus.

**Comment by Kitcham** [comment]
@neoFelhz Oh. As that we face to the world  user, we need to consider users'  local new situation. Personally,I think we should give the right to the user,they can choose if they need to turn it on.
In that , I remain the "Disqus-load- right-now" before,,I just add a new way. Thanks for your comment

**Comment by Kitcham** [comment]
@neoFelhz  Multilingual support for the button is added, also the text is updated

**Comment by Kitcham** [comment]
@viosey  Multilingual support for the button is added, also the text is updated
New feat has already optimized

**Comment by cubesky** [comment]
I think we can judgment if visitor can access google.com, if they cn access google.com, disqus will automatically loaded. If not, we can display this button. 
What do you think about this? @neoFelhz @viosey

**Comment by neoFelhz** [comment]
@cubesky No.
I have hosts that I can visit Google in China,but the hosts I use didn't contains Disqus.
Maybe we should judge the disqus's favicon instead.

**Comment by AayushRd7** [comment]
@cubesky WoHi Hai BC

**Comment by viosey** [comment]
@AayushRd7 What are you talking about?

**Comment by cubesky** [comment]
@AayushRd7 Sorry, I can't understand what are you talking about.

**Pull request merged**
