### PR TITLE
0

### PR DESCRIPTION
**Pull request by wzcv**
**Contributing rules**

- Fork the repo and create your branch from `canary`. Then be sure to put the `canary` branch as the target for your pull request.
- Please be sure to follow the [contributing guidelines](https://github.com/viosey/hexo-theme-material/blob/master/CONTRIBUTING.md), especially for commit message
- Remove the `Contributing rules` part from this description
- Fill out the other parts from this description

> If you don't do so, we might change your pull request's title and using `squash` to merge your changed.

**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [ ] No

____

**Description**

No description.

____

**Verification steps**

No verification steps.

### CODE REVIEW

**Comment by wzcv** [comment]
0

**Comment by cubesky** [comment]
Sorry, We can not understand this pr.

**Comment by AkarinServer** [comment]
@cubesky 他应该是想把这个项目pr一份到他自己那，然后弄反了……

**Comment by neoFelhz** [comment]
@cubesky This guy just forget to switch the base and his fork. And this guy then open it.

**Pull request closed without merging**
