### PR TITLE
remove(layout): remove private layout

### PR DESCRIPTION
**Pull request by neoFelhz**
**Contributing rules**

- Fork the repo and create your branch from `canary`. Then be sure to put the `canary` branch as the target for your pull request.
- Please be sure to follow the [contributing guidelines](https://github.com/viosey/hexo-theme-material/blob/master/CONTRIBUTING.md), especially for commit message
- Remove the `Contributing rules` part from this description
- Fill out the other parts from this description

> If you don't do so, we might change your pull request's title and using `squash` to merge your changed.

**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bug fix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [x] Yes
- [ ] No

____

**Description**

Remove the useless `private` layout.

____

**Verification steps**

No verification steps.

### CODE REVIEW

**Comment by kmahyyg** [comment]
@neoFelhz plz don't remove it.it's really useful if I want to share some private thing to my friend.

**Comment by neoFelhz** [comment]
@kmahyyg No, you can't share it.
If you had read the source code of the `private` layout, you will find how dirty the layout is: simply not to load a tips instead of the post content.
I suggest you using [hexo-blog-encrypt](https://github.com/MikeCoder/hexo-blog-encrypt) plugin. It's better than that.

**Comment by cubesky** [comment]
I think we shouldn't remove it. It is useful for private post what I doesn't need show on list.

**Comment by kmahyyg** [comment]
@neoFelhz ok ,that's nice.

**Pull request merged**
