### PR TITLE
feat(footer_sns): add segmentfault

### PR DESCRIPTION
**Pull request by cntanglijun**
**Contributing rules**

- Fork the repo and create your branch from `canary`. Then be sure to put the `canary` branch as the target for your pull request.
- Please be sure to follow the [contributing guidelines](https://github.com/viosey/hexo-theme-material/blob/master/CONTRIBUTING.md), especially for commit message
- Remove the `Contributing rules` part from this description
- Fill out the other parts from this description

**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bug fix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

____

**Description**

Add a new sns icon for segmentfault

____

**Verification steps**

No verification steps.

### CODE REVIEW

**Comment by neoFelhz** [comment]
Thank you for your contribututions!
Anyway, please using `canary` branch as base branch when open a new PR. `canary` branch is used to test new feat code.

**Comment by neoFelhz** [comment]
Now I have been set your branch to `canary` now.

**Comment by AkarinServer** [comment]
@cntanglijun 你的sf footer请尽量按照sf官方定义的logo来

**Comment by AkarinServer** [comment]
Please change all picture format to svg expect for yours one
请将所有的png后缀更改为svg，因为我们已经全面采用svg格式的icon了，当然你的pr可以保留为png格式

**Pull request closed without merging**
