### PR TITLE
fix(comment):duoshuo comment counts display issues and some other errors

### PR DESCRIPTION
**Pull request by long2ice**
**What kind of change does this PR introduce?** (check one with "x")

- [x] Bug fix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

____

**Description**

1. 使用多说评论系统时无法正确显示评论数目
2. `duoshuo.ejs` 和 `Paradox-post_entry.ejs` 中存在的语法错误

____

**Verification steps**

No verification steps.

### CODE REVIEW

**Comment by cubesky** [comment]
Translate: fix bugs of duoshuo.
1. fix a bug of duoshuo cannot display correct comment counts.
2. fix some grammar error in `duoshuo.ejs` and `Paradox-post_entry.ejs`

**Comment by neoFelhz** [comment]
@cubesky Is it safe enough to directly push the commit into the `master` branch? Although there are no problem with the changed files, but I think we'd better use `canary` as base branch for contributions.

**Comment by pidupuis** [comment]
@neoFelhz We'll have to discuss about the process. It seems better to push a fix into master (and then merge master into canary) and a feature/refactor in canary (which will be merged into master at the time of a release). If a bug exists in master, we need a fix in master, and push a commit from canary into master without merging the entire branch is not that easy...

**Comment by pidupuis** [comment]
@gitmagic-bot are you dead?

**Pull request merged**
