### PR TITLE
feat(sidebar): can hide divider and footer

### PR DESCRIPTION
**Pull request by pidupuis**
**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bug fix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [x] Yes
- [ ] No

____

**Description**

- Sidebar dividers can now be displayed or removed after each sidebar item.
- Footer can be hidden.

____

**Verification steps**

Update the sidebar configuration part by changing `divider` value for the different items.

### CODE REVIEW

**Comment by neoFelhz** [comment]
Maybe you can add missed icon configurations in `_config.template.yml` in this pull requeset,which was forgotten to add in pull #165

**Comment by pidupuis** [comment]
@neoFelhz Could you tell me which one are missing please?

**Comment by neoFelhz** [comment]
In `_config.template.yml `,from line 109 to 127.
It should be:
```yml
# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "#"
            icon: email
    homepage:
        use: true
        icon: home
    archives:
        use: true
        icon: inbox
    categories:
        use: false
        icon: chrome_reader_mode
    pages:
        #About:
            #link: "/about"
            #icon: person
```
I missed configure the three default icons。

**Comment by pidupuis** [comment]
@neoFelhz Oh ok sure :)

**Pull request merged**
