### PR TITLE
ADD“Disqus_click_to_load",增加disqus点击后加载功能

### PR DESCRIPTION
**Pull request by Kitcham**
**Contributing rules**

- Fork the repo and create your branch from `canary`. Then be sure to put the `canary` branch as the target for your pull request.
- Please be sure to follow the [contributing guidelines](https://github.com/viosey/hexo-theme-material/blob/master/CONTRIBUTING.md), especially for commit message
- Remove the `Contributing rules` part from this description
- Fill out the other parts from this description

**What kind of change does this PR introduce?** (check one with "x ")

- [x] Bug fix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [x] CI related changes
- [ ] Other... Add “Dissqus_click_to_load”.

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No
- [x] Maybe

____

**Description**

## English：

1. Add “Dissqus_click_to_load”. Useful as it is, it means using disqus but you need to click the button to load the comments. Useful as it is, it help improve Chinese users' experience(G-F-W)so that avoid to loading Disqus very slow. 

2. The style of “Read Comments” button is based on Material Design, Click-effect will be added next release and I am coding
3. Thanks to button.js git:  https://github.com/davinder17s/material-ripple-effect

## 中文：
1. 增加了Disqus的异步手动加载，点击后加载Disqus评论。对梯子短的用户更加友好，避免部分浏览器卡进度条（via，羽等某同行交友市场推荐app会有这个问题）。（逃
2. 手动加载评论button采用MD风格，点击涟漪效果下版本增加，正在码田辛勤耕作中。
3. 引用了这位dalao的button.js轮子： https://github.com/davinder17s/material-ripple-effect

____

**Verification steps**
## English：
1. You can use “Disqus_click_to_load”. it means disqus will be loaded after you click the button. Turn it on in” /themes/material/_config.yml ,Line 139“
Also remain “disqus load without click”. U can choose to use it.
> comment:
    use: disqus_click   //CHOOSE disqus_click TO TURN ON
    shortname:
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
2. Add the style of “Read Comments” button based on Material Design.

## 中文：
1. 可在主题根目录配置文件”/themes/material/_config.yml ,Line 139行“ 中开启，同时保留原立即加载的功能，可供选择。

> comment:
    use: disqus_click   //填写disqus_click开启
    shortname:
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"

2. 阅读评论按钮采用MD风格

### CODE REVIEW

**Comment by cubesky** [comment]
@Kitcham We now use ajax load queue to load disque and bing background image. You can see it in branch canary. 
我们现在使用异步加载队列加载 Disque 和 Bing 背景图功能，你可以在 canary 分支中看到。
另外请阅读提交守则( Contributing rules )，PR 应基于 canary 修改并提交到 canary

**Comment by cubesky** [comment]
@Kitcham 另外，感谢你的 Pull Request ~ 我们将测试这个 Pull Request 的效果~

**Comment by AkarinServer** [comment]
@cubesky 专业的material insider，成就非凡。

**Comment by Kitcham** [comment]
@cubesky 感谢指导，会修改。已经知道disqus是基于异步加载，但依然有部分浏览器卡进度条的问题。这次PR是提供另外一种方式的加载。

**Pull request closed without merging**
