### PR TITLE
feat(cache): localstorage cache js and css files

### PR DESCRIPTION
**Pull request by EYHN**
**Contributing rules**

- Fork the repo and create your branch from `canary`. Then be sure to put the `canary` branch as the target for your pull request.
- Please be sure to follow the [contributing guidelines](https://github.com/viosey/hexo-theme-material/blob/master/CONTRIBUTING.md), especially for commit message
- Remove the `Contributing rules` part from this description
- Fill out the other parts from this description

> If you don't do so, we might change your pull request's title and using `squash` to merge your changed.

**What kind of change does this PR introduce?** (check one with "x")

- [ ] Bug fix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

____

**Description**

demo: https://eyhn.github.io/hexo-test/
说不定会出现问题，请验证。

____

**Verification steps**

No verification steps.

### CODE REVIEW

**Comment by EYHN** [comment]
ok 我检查了一般 觉得没什么问题了

**Comment by neoFelhz** [comment]
This chang was very important. I think we need to.run a test on browserstack.
@cubesky @viosey

**Comment by cubesky** [comment]
Yes, We should test for this carefully.

**Comment by viosey** [comment]
agree

**Pull request merged**
