### PR TITLE
fix(#336)

### PR DESCRIPTION
**Pull request by neoFelhz**
**Contributing rules**

- Fork the repo and create your branch from `canary`. Then be sure to put the `canary` branch as the target for your pull request.
- Please be sure to follow the [contributing guidelines](https://github.com/viosey/hexo-theme-material/blob/master/CONTRIBUTING.md), especially for commit message
- Remove the `Contributing rules` part from this description
- Fill out the other parts from this description

> If you don't do so, we might change your pull request's title and using `squash` to merge your changed.

**What kind of change does this PR introduce?** (check one with "x")

- [x] Bug fix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x")

- [ ] Yes
- [x] No

____

**Description**

No description.

____

**Verification steps**

No verification steps.

### CODE REVIEW

**Comment by EYHN** [comment]
玄学

**Comment by Halyul** [comment]
@neoFelhz 玄学修复2333

**Comment by neoFelhz** [comment]
@EYHN @Halyul `<a>` 标签里，换行会被当成空格的。这个我和 @viosey 是领教过的。法国小哥也是这么修复 footer_sns icon 的。

**Comment by EYHN** [comment]
通过 `text-decoration` 属性解决似乎更加合理
```
text-decoration: none;
```

**Comment by Halyul** [comment]
@neoFelhz 我同意@EYHN 的方法🙄

**Comment by cubesky** [comment]
@EYHN 上次我这么修被close..

**Comment by neoFelhz** [comment]
@EYHN @Halyul
用 `text-decoration` 不能根治空格的存在，只能让其不显示。

**Comment by EYHN** [comment]
我试了一下发现在 `a` 标签上添加 `display: inline-block;` 样式也可以解决这个问题

**Comment by EYHN** [comment]
逻辑上 `text-decoration: none;` 和 `display: inline-block;` 都是需要的

**Pull request merged**
